### ISSUE TITLE
Quota completed message and response valid entries autocomplete shows SMS prompt messages text.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#562] opened 2017-01-16 18:44 UTC
Found in version 0.5.0-dev-38873bb (build 1384)

Preconditions:
There is a SMS Question Prompt with the following SMS message: `Message of the question`.

Reproduce steps:
Add a Response to the step.
Click on `Valid Entries` field.
Fill with `Message`.
Observe the texts displayed.
Add a `Quota completed message`.
Click on `SMS message` field.
Fill with `Message`.
Observe the texts displayed.

Obtained:
The prompt messages text are displayed in the response `Valid Entries` field and the `Quota completed message` field.

Screenshots:
<img width="984" alt="screen shot 2017-01-16 at 3 31 23 pm" src="https://cloud.githubusercontent.com/assets/518152/21995097/d233caa0-dc01-11e6-9b67-0d07ee5e0b06.png">
<img width="929" alt="screen shot 2017-01-16 at 3 27 25 pm" src="https://cloud.githubusercontent.com/assets/518152/21995098/d2363466-dc01-11e6-9609-7d1d11792c95.png">

**Comment by mverzilli** [comment] 2017-01-17 13:11
If I'm interpreting the issue well, this is by design. The intuition is that you if you translate "Hello" to "Hola" somewhere, you're likely to translate "Hello" to "Hola" everywhere else. I'll close this but feel free to reopen if misunderstood the report.

**Closed** 2017-01-17 13:11 UTC
Labels: bug, minor

**Comment by mverzilli** [comment] 2017-01-17 17:47
@mmuller observed that people are unlikely to reuse the same texts for a question prompt and a quota completed message, for example. So putting them all together in the same index adds noise to the list of suggestions. 

We could keep different indexes to make this smarter, thus I'm reopening this as an enhancement suggestion.
