### ISSUE TITLE
Improve readability on input textboxes for questions

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1017] opened 2017-05-24 21:04 UTC
> The size of the SMS/IVR text boxes is too small, and poses difficulties for QC (quality control). When people do QC in the tool, they often are looking at the text. But you can only see 1/3 of the SMS message at a time. Having to navigate around using arrows is burdensome for users and in one case, has caused someone to delete text.

**Comment by asterite** [comment] 2017-05-26 16:12
Duplicate of #898 ? It's already fixed in 0.10.0

**Closed** 2017-05-30 15:08 UTC
Labels: design, enhancement

**Comment by mmuller** [comment] 2017-06-09 14:57
Verified on #898
