### ISSUE TITLE
[Quiz] Autocomplete in responses not working for Mobile Web input field

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#988] opened 2017-05-13 00:39 UTC
Version: 0.8.2 (build 2171)

1. Create a questionnaire
2. Set 'IVR, SMS and Mobile Web' modes 
3. Add a Multiple choice step 'Foo'
4. Add a response for 'Yes' for all three modes 
5. Add another Multiple choice step, 'Bar'
6. Add another response for 'Yes' by just filling out the 'Response' field

Expected:
All other mode's response input fields are autocompleted with what was set in step '4.'

Obtained:
'Mobile Web' response input field is not autocompleted.

**Comment by asterite** [comment] 2017-05-15 13:32
Duplicate of #720 (it's a known issue and depends on how we are going to show multilines and styled text there)

**Closed** 2017-05-15 13:43 UTC
Labels: bug, normal
