### ISSUE TITLE
[Survey] Quotas don't work properly if they are defined using the last question.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1059] opened 2017-06-07 18:52 UTC
Found in version: 51b2425

Preconditions:
There is a Questionnaire `Foo`.
`Foo` has one step (a numeric step `Age`0.

Reproduce steps:
Create a Survey.
Select the Questionnaire Foo.
Upload 10 respondents.
Specify the following quotas: 
- Age:20,50 Target:1.
- Age:50,70 Target:1.

Complete the wizard.
Start the Survey.
As respondent `1` answer the question Age with the value 40.
As respondent `2` answer the question Age with the value 40.

Obtained:
- The Survey is still running.
- The respondents `1` and `2` are marked as `Completed`.
- The respondent `2` doesn't receive the message defined in the `Quota completed step`.
- Other respondents are still `Registered`. They are not enqueued.

Expected:
- The respondents `1` is marked as `Completed`.
- The respondents `2` is marked as `Rejected`.
- Other respondents should be contacted in order to cover the Quotas.

**Comment by waj** [comment] 2017-06-08 13:44
It's ok that the respondent `2` is marked as `Completed` because even when the respondent would not be considered for the rest of the questionnaire the answer is still stored. And that means the full questionnaire is now completed. That also means the respondent will not receive the messages in `Quota completed step`. All this is by design and it's actually a corner case not very useful in real scenarios.

However, other respondents should still be contacted until all the quotas are completed.

**Closed** 2017-06-15 20:38 UTC
Labels: bug, in progress, normal

**Comment by mmuller** [comment] 2017-06-19 20:01
Working properly in version 6e66205
