### ISSUE TITLE
User with existing email must not be able to be created

### ISSUE THREAD

**Issue by asterite** [instedd/ask#101] opened 2016-10-13 17:29 UTC
Steps to reproduce:
1. Register a user with an email
2. Logout
3. Register a user with the same email

Expected: an error saying the email is already taken
Actual: the user is created

**Comment by asterite** [comment] 2016-10-14 18:23
I tried to fix it but it seems it can't be done unless we fix addict or use another library: https://github.com/trenpixster/addict/issues/85

**Comment by fgasperij** [comment] 2016-10-28 13:02
We have an Ecto `unique_constraint` on the changeset and a `unique_index` on the table, I suppose that doesn't work because Addict disregards the User model changeset since it has other ways to add validations to it's normal flow.

We have some alternatives to deal with this:

- wait for https://github.com/trenpixster to solve the issue (he says here https://github.com/trenpixster/addict/issues/86 it will be fixed soon).
- try to add an extra_validation as explained here https://github.com/trenpixster/addict/blob/master/configs.md. It's a compromise because it introduces the possibility of race conditions but that's an unlikely scenario in this app.
- fork it and fix it ourselves. The validation is there (https://github.com/trenpixster/addict/blob/master/lib/addict/interactors/validate_user_for_registration.ex#L24) but evidently is not being applied.

I would wait a couple of weeks if this is not urgent and, if the issue isn't resolved by then, fork it and fix it.

**Comment by mverzilli** [comment] 2017-01-27 20:14
Closed via #597

**Closed by mverzilli** 2017-01-27 20:14 UTC
Labels: bug, major

**Comment by mmuller** [comment] 2017-02-23 17:07
Working properly in version b706119
