### ISSUE TITLE
[Questionnaire] Changing language and trying to edit an ivr message or upload an audio raises an error

### ISSUE THREAD

**Issue by nekron** [instedd/ask#412] opened 2016-12-07 18:35 UTC
The error is `cannot read property ivr of 'undefined'`

Steps to reproduce:

- Create a numeric step.
- Add a language
- Add an ivr text

If you add an sms text first, the error won't occur and the ivr text can be entered just fine.

**Comment by nekron** [comment] 2016-12-07 19:01
Trying to edit sms and ivr choice texts in a different language leads to the same error.

**Comment by juanboca** [comment] 2016-12-13 14:49
I can't reproduce this issue. 
Please, can you provide more details?

**Comment by juanboca** [comment] 2016-12-14 15:39
I was able to reproduce it. And should be fixed when fixint #382

**Closed** 2016-12-14 19:47 UTC
Labels: bug, in progress, major
