### ISSUE TITLE
Surveda logo looks a bit off in collaborator email 

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#1108] opened 2017-06-23 15:40 UTC
Found in Version: 0.10.0-dev-8e75560 (build 2581)

1. As project owner add a collaborator
2. Open notification email

Obtained:
Surveda logo does not look proportioned.

![screen shot 2017-06-23 at 12 36 55 pm](https://user-images.githubusercontent.com/9214460/27489424-edf40bac-5810-11e7-8860-2213ad03144e.png)

**Comment by waj** [comment] 2017-06-23 17:56
Duplicate of #1082

**Closed by waj** 2017-06-23 17:56 UTC
Labels: bug, minor
