### ISSUE TITLE
[Respondents] Interactions download button has wrong description and inconsistent title

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#789] opened 2017-03-27 17:01 UTC
Version: 0.7.2-dev-8a3fbff (build 1887)

- [ ] Interactions download option has the same description as the Incentives file option
- [ ] All three previous options don't have the 'Download CSV for...' description on its title. It's redundant when the popup window already has a 'Download CSV. Download survey respondents data as CSV' title.
![screen shot 2017-03-27 at 1 54 46 pm](https://cloud.githubusercontent.com/assets/9214460/24368097/91ee74ec-12f5-11e7-8270-5d549ce6690e.png)

**Comment by steesdale** [comment] 2017-03-27 17:03
The descriptive text for the last option is a duplicate of the third.

**Closed** 2017-03-28 18:54 UTC
Labels: bug, normal

**Comment by mmuller** [comment] 2017-04-07 13:52
Working properly in version 9c248ee
