### ISSUE TITLE
[Survey] Count partial as completed in the cutoff rules.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1093] opened 2017-06-15 18:29 UTC
Found in version: b4a2461

Preconditions:

- There is a Questionnaire `Q`.
- `Q` has a Numeric step `Age`.
- `Q` has a `Partial` Flag step. 
- Within `Age` the Skip logic has selected the step Partial.
- After the `Partial` step there are more steps.

Reproduce steps:

- Go to create a Survey.
- Upload 10 respondents.
- Select the `Number of completes` option.
- Fill the field with the value `1`.
- Check the `Count partial as completed` option.
- Complete the wizard.
- Start the Survey.
- As the first Respondent answer the question `Age` and don't complete the Survey.

Obtained result:

- The Respondent is marked as `Partial`.
- The Survey is not marked as `completed` and it is still running.

Expected:

- The Survey should be marked as completed.

Screenshot:

<img width="1359" alt="screen shot 2017-06-15 at 3 00 53 pm" src="https://user-images.githubusercontent.com/518152/27195952-1ae09df2-51df-11e7-925d-aee8a3524bc6.png">

**Comment by waj** [comment] 2017-10-31 22:18
This is by design. The survey is marked as completed when there are no more active respondents.

**Closed** 2017-10-31 22:18 UTC
Labels: enhancement, invalid
