### ISSUE TITLE
[Collaborators] Each click on the single use link generates a record on the db

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#546] opened 2017-01-13 18:21 UTC
Each time the user clicks on the link `single use link`, a record is generated on the `invites` table, with the same code and level.

![screen shot 2017-01-13 at 3 14 49 pm](https://cloud.githubusercontent.com/assets/488553/21940601/d82673b4-d9a3-11e6-96ce-01189ef53ae0.png)

![screen shot 2017-01-13 at 3 15 02 pm](https://cloud.githubusercontent.com/assets/488553/21940600/d825b65e-d9a3-11e6-9c66-a8a9c6c4f10a.png)

**Comment by asterite** [comment] 2017-01-13 21:01
Related to #541

**Comment by mverzilli** [comment] 2017-01-17 13:20
Closing as a duplicate of #541.

**Closed by mverzilli** 2017-01-17 13:20 UTC
Labels: bug, normal
