### ISSUE TITLE
[Questionnaire] Place holder overlaps color preview in mobile web settings.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1006] opened 2017-05-19 15:43 UTC
Version 0.9.0

`Primary color` and `Secondary color` are not correctly placed.

<img width="943" alt="screen shot 2017-05-19 at 12 37 50 pm" src="https://cloud.githubusercontent.com/assets/518152/26255646/a4821a72-3c90-11e7-89dc-050f3725fe4e.png">

**Comment by asterite** [comment] 2017-05-22 15:02
Duplicate of #1000

**Closed by asterite** 2017-05-22 15:02 UTC
Labels: bug, minor
