### ISSUE TITLE
[Quiz] While editing SMS prompt for the first time, it keeps showing an error

### ISSUE THREAD

**Issue by juanboca** [instedd/ask#504] opened 2017-01-06 17:51 UTC
On a newly created step, the prompt shows an error before editing it. When the user clicks to edit, the error disappears, but after the user starts typing, the error appears again.

![screen shot 2017-01-06 at 2 47 58 pm](https://cloud.githubusercontent.com/assets/488553/21727249/34ab0b34-d41f-11e6-8504-f33e7d666dc9.png)
![screen shot 2017-01-06 at 2 48 20 pm](https://cloud.githubusercontent.com/assets/488553/21727248/348f12f8-d41f-11e6-9916-670650b508b8.png)

**Comment by asterite** [comment] 2017-01-11 15:57
I can't reproduce this. I click on "Add step", the new step appears and nothing is red inside it. What are the exact steps to reproduce this?

**Comment by mverzilli** [comment] 2017-01-11 17:19
I fixed that as part of #315. The reason I didn't close this is because the controls validation labels behave somewhat erratically, which is more related to "When the user clicks to edit, the error disappears, but after the user starts typing, the error appears again". 

I think the issue as it is right now is quite minor and solving it for all possible sequences of interactions and states is going to be quite difficult.

**Closed** 2017-01-27 21:06 UTC
Labels: bug, in progress, minor

**Comment by mmuller** [comment] 2017-02-23 17:12
Working properly in version b706119
