### ISSUE TITLE
[Questionnaire] SMS choices translation is not being displayed when changing languages

### ISSUE THREAD

**Issue by nekron** [instedd/ask#402] opened 2016-12-07 15:10 UTC
Download the resources CSV, translate the responses of a multiple choice step, then upload it again.

It won't display the SMS and Phone call texts when switching the default language.

English (original default language):
![screen shot 2016-12-07 at 12 28 39 pm](https://cloud.githubusercontent.com/assets/488553/20973800/bc47eb16-bc78-11e6-9ebe-c2d001087fdd.png)

Spanish:
![screen shot 2016-12-07 at 12 28 47 pm](https://cloud.githubusercontent.com/assets/488553/20973799/bc46b156-bc78-11e6-89a6-f8a41276217e.png)

**Comment by asterite** [comment] 2016-12-12 15:07
I think we fixed this in 62317b08b23211088cc31829c949db24307d7fd8

@mmuller @pmallol Could you please try to reproduce this in different ways? I wasn't able to reproduce it. If it's not reproducible, please close it and mark it as invalid. Thank you! 😸

**Comment by mmuller** [comment] 2016-12-12 20:11
I couldn't reproduce this issue in version 0.4.0-dev-9e45973

**Closed by mmuller** 2016-12-12 20:11 UTC
Labels: bug, normal
