### ISSUE TITLE
Problem setting ineligible disposition and partial with flag.

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#756] opened 2017-03-16 22:33 UTC
**Environment**: Version: 0.7.0 (build 1786)

Steps: 
Using this questionnaire: http://ask-demo.instedd.org/projects/19/questionnaires/119/edit
Set up a phone call survey. Go through the questionnaire, selecting:
1 for **2Demog Sex**
15 for **2Demog Age**

Expected:
End the survey with an ineligible disposition.

Actual
End the survey with a completed disposition.

**Comment by spalladino** [comment] 2017-03-20 14:36
@adam704a could you export the questionnaire (not the CSV) and upload it here, so we can import it into another project and try to reproduce it? Thank you!

**Comment by adam704a** [comment] 2017-03-20 15:11
@spalladino 

[ineligible-disposiiton-broke.zip](https://github.com/instedd/ask/files/855415/ineligible-disposiiton-broke.zip)

Also, failed calls not being marked as such in the export files too.

**Comment by mmuller** [comment] 2017-03-20 16:50
Duplicate of #747

**Comment by spalladino** [comment] 2017-03-20 17:03
@adam704a note that, in your example, after the "Ineligible - Age" step, the questionnaire jumps to "End Message", and then proceeds to "Complete", where the disposition is set to Complete, even if it was Ineligible before. 

This is a known issue (#747, as noted by @mmuller). We'll schedule this to be fixed in the next release, but in the meantime, you can work around it for now by ensuring that the _Complete_ step is not reached after the _Ineligible_ one. For instance, you can change the skip logic in the "Ineligible - Age" to jump to a *new* "End Message - Ineligible" step, with *End survey* configured as skip logic. Let me know if this is clear!

**Comment by spalladino** [comment] 2017-03-20 17:04
Note that the same will happen with the Partial disposition.

**Closed** 2017-03-20 17:03 UTC
Labels: duplicate

**Comment by adam704a** [comment] 2017-03-20 17:37
Makes sense. Thanks!!
