### ISSUE TITLE
The Interactions file is not capturing all Interactions

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1126] opened 2017-08-04 17:08 UTC
Reported by Charles:
"The Interactions file is not capturing all Interactions. (Martin and I discussed this briefly on skype.) For example, there were some IVR calls not captured in Interactions file.
All contact attempts need to be documented in interactions file."

**Comment by nditada** [comment] 2017-08-22 15:32
duplicate of #1127

**Closed by nditada** 2017-08-22 15:32 UTC
Labels: enhancement
