### ISSUE TITLE
[Survey] Survey is in invalid state

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#413] opened 2016-12-07 18:37 UTC
Survey http://ask-stg.instedd.org/projects/89/surveys/421 was started, yet marked as complete even before receiving any messages. Percentages were displayed as NaN%.

Note that it was at a time where Nuntium was sending messages that caused the broker to crash (see logs below).

<img width="759" alt="screen shot 2016-12-07 at 3 34 59 pm" src="https://cloud.githubusercontent.com/assets/429604/20981314/ed9ac412-bc92-11e6-8d7a-b68b73e8f0ec.png">

<details>
18:41:19.474 request_id=adel6e1hkd46te9q65aide0cbetoesbh [info] GET /callbacks/nuntium/
18:41:19.508 [error] GenServer Ask.Runtime.Broker terminating
** (RuntimeError) Skip logic: invalid step id.
    (ask) lib/ask/runtime/flow.ex:71: Ask.Runtime.Flow.next_step_by_skip_logic/3
    (ask) lib/ask/runtime/flow.ex:84: Ask.Runtime.Flow.advance_current_step/3
    (ask) lib/ask/runtime/flow.ex:131: Ask.Runtime.Flow.accept_reply/2
    (ask) lib/ask/runtime/flow.ex:16: Ask.Runtime.Flow.step/2
    (ask) lib/ask/runtime/session.ex:92: Ask.Runtime.Session.sync_step/2
    (ask) lib/ask/runtime/broker.ex:151: Ask.Runtime.Broker.do_sync_step/2
    (ask) lib/ask/runtime/broker.ex:53: Ask.Runtime.Broker.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
18:41:19.511 [error] #PID<0.1859.0> running Ask.Endpoint terminated
Server: ask-stg.instedd.org:80 (http)
Request: GET /callbacks/nuntium/?application=Ask+%28dev%29&application=Ask+%28dev%29&body=25&channel=FakeChannel&country=RB&from=sms%3A%2F%2F9992000&guid=d1e8dcbf-e4c7-866e-50cf-5ebd6d9d1877&subject=&to=sms%3A%2F%2F0
** (exit) exited in: GenServer.call({:global, Ask.Runtime.Broker}, {:sync_step, %Ask.Respondent{__meta__: #Ecto.Schema.Metadata<:loaded, "respondents">, completed_at: nil, id: 113420, inserted_at: #Ecto.DateTime<2016-12-07 18:13:42>, phone_number: "9992000", quota_bucket: #Ecto.Association.NotLoaded<association :quota_bucket is not loaded>, quota_bucket_id: nil, responses: #Ecto.Association.NotLoaded<association :responses is not loaded>, sanitized_phone_number: "9992000", session: %{"channel_id" => 64, "fallback_channel_id" => nil, "fallback_retries" => nil, "flow" => %{"current_step" => 2, "language" => "en", "mode" => "sms", "questionnaire_id" => 124}, "respondent_id" => 113420, "retries" => []}, state: "stalled", survey: #Ecto.Association.NotLoaded<association :survey is not loaded>, survey_id: 419, timeout_at: nil, updated_at: #Ecto.DateTime<2016-12-07 18:29:32>}, {:reply, "25"}}, 5000)
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Skip logic: invalid step id.
            (ask) lib/ask/runtime/flow.ex:71: Ask.Runtime.Flow.next_step_by_skip_logic/3
            (ask) lib/ask/runtime/flow.ex:84: Ask.Runtime.Flow.advance_current_step/3
            (ask) lib/ask/runtime/flow.ex:131: Ask.Runtime.Flow.accept_reply/2
            (ask) lib/ask/runtime/flow.ex:16: Ask.Runtime.Flow.step/2
            (ask) lib/ask/runtime/session.ex:92: Ask.Runtime.Session.sync_step/2
            (ask) lib/ask/runtime/broker.ex:151: Ask.Runtime.Broker.do_sync_step/2
            (ask) lib/ask/runtime/broker.ex:53: Ask.Runtime.Broker.handle_call/3
            (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4

</details>

**Comment by spalladino** [comment] 2016-12-07 18:54
Happened only with a survey that was preemptively marked as completed, even before receiving any messages. See http://ask-stg.instedd.org/projects/89/surveys/421.

**Comment by juanboca** [comment] 2016-12-16 15:33
Cannot reproduce this issue anymore.
It seems that it was a temporary issue related with the error in Nuntium, and the UI error was fixed in other issue.

**Closed by juanboca** 2016-12-16 15:33 UTC
Labels: bug, in progress, normal
