### ISSUE TITLE
The graphical interface for retries is confusing.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1165] opened 2017-09-08 12:27 UTC
Reported by Adam Preston:

> I don’t think this was designed all at once. As a user, the graphical interface should represent the flow of the calls, but it is more confusing than helpful. If the UI has a graphic, it could be a single flow rather than chopped up into multiple graphics.

**Comment by nditada** [comment] 2017-09-08 22:09
Duplicate of #1132

**Closed by nditada** 2017-09-08 22:09 UTC
Labels: enhancement
