### ISSUE TITLE
[Autosave] Warn on unsaved changes

### ISSUE THREAD

**Issue by waj** [instedd/ask#1226] opened 2018-02-05 18:31 UTC
Warn if the user tries to close the browser with unsaved changes.

**Comment by mmuller** [comment] 2018-02-21 01:17
Currently (version 602d30e) the warning message is not displayed when the user tries to close the browser (Chrome 63.0.3239.132).

**Comment by juanboca** [comment] 2018-02-21 13:53
What are the steps to reproduce it? It works properly for me on surveda-stg

**Comment by mmuller** [comment] 2018-02-21 14:01
@juanboca 
Steps to reproduce:
Navigate to a Questionnaire.
Replace a Question Prompt.
Close the browser.

Obtained:
The warning message is not displayed.

**Comment by juanboca** [comment] 2018-02-21 14:10
Since the request to save the Questionnaire goes to the server and back very quick, the closing of the browser should be in the exact moment that it says "Saving..." on the top right corner.
This feature is for the times where the server can be slow or the user has a slow connection, so for testing it in staging you need to be very quick on the steps

![](http://g.recordit.co/Q2nqMsNedz.gif)

**Comment by mmuller** [comment] 2018-02-21 14:21
Working properly in version 602d30e

**Closed** 2018-02-21 14:21 UTC
