### ISSUE TITLE
Mobile Web: Interactions Download says SMS and has Twilio channel for all

### ISSUE THREAD

**Issue by edjez** [instedd/ask#911] opened 2017-04-20 20:04 UTC
Expected:
- SMS channel and mode for "Prompt" / "Contact"
- Mobile Web mode, and Channel=URL (with no token) for mobile web interactions
Actual:
All interactions appear as mode=sms and channel=twilio

**Comment by waj** [comment] 2017-04-20 20:10
Duplicate of #875

**Closed by waj** 2017-04-20 20:10 UTC
