### ISSUE TITLE
[Questionnaire] Issues with button 'Upload a file' in Voice Message option

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#288] opened 2016-11-14 18:09 UTC
Version: 0.3.0-dev-4f8644f (build 710)

- [ ] The button does not look like a dropdown. The user only figures out there is another option 'Text to speech' after clicking it.
- [ ] The icon and text 'Text to speech' are overlay

![screen shot 2016-11-14 at 3 00 13 pm](https://cloud.githubusercontent.com/assets/9214460/20276645/e12d4df4-aa7b-11e6-82dd-34ad4adb55c5.png)

**Comment by waj** [comment] 2016-11-15 17:36
Duplicate of #257

**Closed by waj** 2016-11-15 17:36 UTC
Labels: bug, duplicate, minor
