### ISSUE TITLE
Questionnaire Builder - Provide a live preview link / interface

### ISSUE THREAD

**Issue by edjez** [instedd/ask#149] opened 2016-10-18 19:56 UTC
Put in a popup SMS simulator; and a number to call; to test "live" the survey out as currently saved
{and mobile web popup link in the future}

**Comment by edjez** [comment] 2016-11-07 17:38
Same thing for IVR - type in your phone number and press 'test' and use a InSTEDD twilio channel to call that number and run the questionnaire

**Comment by asterite** [comment] 2017-05-18 16:42
Duplicate of #999

**Closed by asterite** 2017-05-18 16:42 UTC
Labels: enhancement
