### ISSUE TITLE
[Questionnaire] An error is thrown in the 'Language selection' step.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#382] opened 2016-12-06 19:28 UTC
Found in version:
0.4.0-dev-e90cbba

Preconditions:
There is a Questionnaire 'Q'.
'Q' has two languages ('English' and 'Spanish').

Reproduce steps:
Go to edit the Questionnaire 'Q'.
Expand the 'Language selection' step.
Click on the 'Voice message' field.
Click on the arrow to load the second language.

Actual result:
An error is displayed.
The following error is logged in the browser's console:
`ErrorEventbubbles: falsecancelBubble: falsecancelable: truecolno: 27145composed: falsecurrentTarget: WindowdefaultPrevented: trueerror: TypeError: Cannot read property 'ivr' of undefined
    at http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:27145
    at a (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:23304)
    at I (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:26991)
    at R (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:25040)
    at S (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:24762)
    at E (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:24714)
    at d (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:17986)
    at http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:17928
    at http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:75:30156
    at http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:68:2085
    at c (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:68:3560)
    at http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:76:20121
    at http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:76:20121
    at http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:65:18596
    at http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:67:30974
    at Object.changeStepPromptIvr (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:67:32004)
    at i.value (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:71:19009)
    at onBlur (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:71:22184)
    at Object.e (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:59:29136)
    at l (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:58:2713)
    at Object.s [as executeDispatchesInOrder] (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:58:2928)
    at p (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:57:31026)
    at v (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:57:31152)
    at Array.forEach (native)
    at e (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:61:13577)
    at Object.processEventQueue (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:58:211)
    at e (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:59:29519)
    at Object.handleTopLevel [as _handleTopLevel] (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:59:29636)
    at o (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:59:30204)
    at e.perform (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:61:8481)
    at Object.batchedUpdates (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:59:26823)
    at Object.o [as batchedUpdates] (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:60:19381)
    at dispatchEvent (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:59:31229)
    at HTMLDocument.t (http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d:50:15570)eventPhase: 0filename: "http://ask-stg.instedd.org/js/app-c38d8ac1775d345a8cb901fa710fc9e5.js?vsn=d"isTrusted: truelineno: 75message: "Uncaught TypeError: Cannot read property 'ivr' of undefined"path: Array[1]returnValue: falsesrcElement: Windowtarget: WindowtimeStamp: 524559.9550000001type: "error"__proto__: ErrorEvent`

Additional information:
https://sentry.io/instedd/ask/issues/190802424/

Screenshot:
<img width="1652" alt="screen shot 2016-12-06 at 4 28 16 pm" src="https://cloud.githubusercontent.com/assets/518152/20940303/fce15ef8-bbd0-11e6-96ba-1dcc5f4b81ce.png">

**Comment by juanboca** [comment] 2016-12-12 13:56
Might be related with #412

**Comment by juanboca** [comment] 2016-12-12 19:49
This should be fixed by #394

**Comment by asterite** [comment] 2016-12-13 19:43
I can't reproduce this with the given instructions

**Comment by mmuller** [comment] 2016-12-14 12:49
This issue is not reproducible in version 0.4.0-dev-9e45973

**Comment by juanboca** [comment] 2016-12-14 14:02
I can still reproduce it on Staging.
This process should be done twice:
Click on the 'Voice message' field.
Click on the arrow to load the second language.

When the user tries to set back the original default language (English), the error is displayed.

![screen shot 2016-12-14 at 10 58 29 am](https://cloud.githubusercontent.com/assets/488553/21184783/c621e726-c1ec-11e6-9091-ba5b214f73e9.png)

**Closed** 2016-12-14 19:47 UTC
Labels: bug, in progress, major

**Comment by mmuller** [comment] 2016-12-16 22:26
Ok in version 0.4.0-dev-ab1556c
