### ISSUE TITLE
IVR Quota Message Missing File Upload

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#435] opened 2016-12-16 04:56 UTC
The IVR Quota message is missing a file upload option.  
<img width="781" alt="screen shot 2016-12-15 at 10 55 04 pm" src="https://cloud.githubusercontent.com/assets/3987608/21252091/9a88b5f8-c319-11e6-879d-72daa48df88b.png">

**Expected:**  
When setting the quota message: 
- I could select text to speech and write a message, 
- Or I could upload a file

**Comment by waj** [comment] 2016-12-16 15:13
Duplicate of #385 (already in progress)

**Closed by waj** 2016-12-16 15:13 UTC
