### ISSUE TITLE
Process user numeric response on IVR after the max number of keypresses

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#817] opened 2017-03-31 23:15 UTC
Given a multiple choice option, where the numbers for all options are single-digit, the user's response can be processed right away after the first digit is entered, without having to wait the 5 seconds timeout. Same applies to numeric questions with a max value.

Send the maxDigits options to Verboice, using the number of digits of the longest option (if a multiple choice question), or the number of digits of the max accepted value (if a numeric question).

**Comment by asterite** [comment] 2017-05-18 16:30
Duplicate of #961 (fixed already)

**Closed by asterite** 2017-05-18 16:30 UTC
Labels: enhancement, on hold
