### ISSUE TITLE
Optimize response for multiple choice questions

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#824] opened 2017-04-04 17:04 UTC
From the Zambia Pilot notes here: https://docs.google.com/document/d/1rV86eTkoXorvohP_AhK7GrYpejZ9eR_eWWaHfQxI6JQ/edit?disco=AAAAA9A6Rv0 

> Juan and Matias mentioned that on the Airtel channel there was a delay of several seconds before the first message started playing. 
> 
> Also, Ask waits for 5 seconds after an option is entered to send the response. This could also be a cause of the breakoffs after the user entered the first option. A simple solution for this would be, just for multiple choice questions, to process the response right after it was entered if we know that the question has only 1-digit options.

**Comment by spalladino** [comment] 2017-04-04 17:18
Closing as duplicate of #817, @adam704a please follow up on that issue!

**Closed by spalladino** 2017-04-04 17:18 UTC
Labels: duplicate
