### ISSUE TITLE
Same survey question is sent two times to same respondent

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#125] opened 2016-10-13 19:01 UTC
Version: 0.2.0-prod

1. Create a Survey 
2. Select or create a questionnaire
3. Import more than 20 respondents and select channel configured with Nuntium Local Gateway app
4. Save Survey and click Start in Local Gateway

Obtained:
After answering the first 10 respondents questions are sent to another 10 respondents and two of them received the same question twice.

![screen shot 2016-10-13 at 4 00 41 pm](https://cloud.githubusercontent.com/assets/9214460/19362742/3a72239e-915e-11e6-9a91-0e0a6fd1c7e1.png)

![screen shot 2016-10-13 at 4 00 03 pm 1](https://cloud.githubusercontent.com/assets/9214460/19362720/2645d5dc-915e-11e6-9dc8-7b95291c98d7.png)

![screen shot 2016-10-13 at 3 55 30 pm](https://cloud.githubusercontent.com/assets/9214460/19362582/96bb55b8-915d-11e6-99f8-8d89bf28360a.png)

**Comment by waj** [comment] 2016-10-14 22:58
I wasn't able to reproduce this. Are you sure there are no duplicate respondents in your csv file?

**Comment by pmallol** [comment] 2016-10-20 17:00
@waj , yes I'm sure. I'll try to reproduce it later this day.

**Comment by waj** [comment] 2016-10-25 18:19
@pmallol I was just digging into the staging database and I found that respondents 9997543534 and 9994255654674 are duplicated in all the surveys. I'll close this issue because for me it's clear that was the reason of the duplicate messages. If your original respondents file didn't have those duplicates, please open a separate issue attaching the csv file. Thanks!

**Closed by waj** 2016-10-25 18:19 UTC
Labels: bug, major, ready
