### ISSUE TITLE
Overview screen not displaying the right mode.

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#803] opened 2017-03-30 14:04 UTC
For this [survey](http://surveda-zambia.org/projects/2/surveys/80/settings), the overview screen indicates that the primary mode is IVR.

![screen shot 2017-03-30 at 8 02 43 am](https://cloud.githubusercontent.com/assets/276936/24507980/51481174-151f-11e7-90ac-6f5fb129b512.png)

But in the settings screen, it is properly reported that the survey is SMS with phone call fallback.

![screen shot 2017-03-30 at 8 03 48 am](https://cloud.githubusercontent.com/assets/276936/24508020/6f13f3c6-151f-11e7-9cb7-f56eca136d68.png)

**Comment by asterite** [comment] 2017-03-30 14:15
Duplicate of #752

**Comment by asterite** [comment] 2017-03-30 14:16
@adam704a It's already being worked on :-)

**Closed by asterite** 2017-03-30 14:15 UTC
