### ISSUE TITLE
[Questionnaire] Uploading a file w/translations in spanish erases IVR reponses

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#467] opened 2016-12-23 19:08 UTC
Version: 0.4.1 (build 1121)

Preconditions:
There is a Project already created

1. Create a Questionnaire with both modes SMS and IVR
2. Add a Multiple choice step (e.g Do you smoke?)
3. Add valid responses Yes and No with 1 for 'Yes' and 2 for 'No' under column Phone Call
4. Add the Spanish language
5. Download the contents as CSV
6. Open the downloaded file and complete the rows with the text in spanish
7. Upload contents as CSV
8. Change main language to Spanish

Observed:
Open question Do you smoke and check on valid responses, the Phone Call valid options 1 and 2 are no longer there.

**Comment by asterite** [comment] 2017-01-11 12:56
I couldn't reproduce this in master, so this should be fixed in 0.5. Please test again once we deploy 0.5. Thank you! 😸

**Closed by asterite** 2017-01-11 12:56 UTC
Labels: bug, normal

**Comment by pmallol** [comment] 2017-01-27 17:57
Ok in Version: 0.6.0-dev-b86ae04 (build 1467)
