### ISSUE TITLE
[Quiz] Expanded step disappears while dragging

### ISSUE THREAD

**Issue by waj** [instedd/ask#471] opened 2016-12-27 14:07 UTC

**Comment by juanboca** [comment] 2017-01-03 17:41
Cannot reproduce it anymore on local environment. 
It was probably fixed by the step editor refactors

**Closed by juanboca** 2017-01-03 17:41 UTC
Labels: bug, ready

**Comment by mmuller** [comment] 2017-01-17 21:42
The issue is not present in version 0.5.0-dev-38873bb (build 1384)
