### ISSUE TITLE
[Quiz] Wrong primary mode is displayed when selecting Mobile web as primary

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/ask#884] opened 2017-04-18 18:16 UTC
Steps to reproduce:

- Launch a Survey with Mobile web mode as primary and SMS message as fallback

Settings after launching the survey should look like this:
![wrong-primary-mode-2](https://cloud.githubusercontent.com/assets/8591752/25146428/342aadd8-244a-11e7-95c2-794c498cfa6c.png)

Obtained in Survey Overview:
![wrong-primary-mode-1](https://cloud.githubusercontent.com/assets/8591752/25146533/994ed9aa-244a-11e7-9ce5-6d5a0e5280b0.png)

Expected:
Mobile web should appear as primary mode

**Comment by nekron** [comment] 2017-04-18 18:31
Duplicate of #879

**Closed** 2017-04-18 18:32 UTC
Labels: bug, duplicate, minor, ready
