### ISSUE TITLE
Basic Survey Design

### ISSUE THREAD

**Issue by nditada** [instedd/ask#24] opened 2016-08-11 14:40 UTC
- [ ] Chooses a questionnaire from the survey
- [ ] Choose channel for each mode of the questionnaire
- [ ] Set a goal: number of completed results 
- [ ] Calculate batch size:  use 10 for now, we'll evolve the heuristics for this.

**Comment by waj** [comment] 2016-09-09 15:02
Duplicate of #17

**Closed** 2016-09-09 15:02 UTC
