### ISSUE TITLE
[Survey] I completed my survey, but the play button does not appear

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#298] opened 2016-11-14 18:49 UTC
<img width="1195" alt="screen shot 2016-11-14 at 15 48 53" src="https://cloud.githubusercontent.com/assets/651693/20278034/ea4bf286-aa81-11e6-9b79-25f675a0fe18.png">

**Comment by lmatayoshi** [comment] 2016-11-14 19:02
Duplicate of #271

**Closed by lmatayoshi** 2016-11-14 19:02 UTC
Labels: duplicate
